// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewaptlwjbflgljpborqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YXB0bHdqYmZsZ2xqcGJvcnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyODY2MjYsImV4cCI6MjA1MTg2MjYyNn0.A4uWQYMmW5Y_yO9CBq6Ys21TZT_Kn370Gn30WHSfX_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);